readme, madiera-run-dev

diff --git a/bin/madeira-run-dev b/bin/madeira-run-dev
--- a/bin/madeira-run-dev
+++ b/bin/madeira-run-dev
@@ -1,44 +1,32 @@
 #!/usr/bin/env bash
 
-function madeira_init {
+set -e
 
-    app="${1}"
+app=$(basename "${PWD}")
+docker_dir="${PWD}/docker"
 
-    if [[ ! "${app}" ]]; then
-      echo "Usage: $0 <app name>"
-      return 1
-    fi
+if [ ! -d "${docker_dir}" ]; then
 
-    app_dir="${HOME}/Development/${app}/docker"
+  echo "${docker_dir} not found or is not a directory"
+  exit 1
+fi
 
-    if [ ! -d "${app_dir}" ]; then
+source "${docker_dir}/common.src"
 
-      echo "${app_dir} not found or is not a directory"
-      return 1
-    fi
-}
+if ! which xfce4-terminal >/dev/null; then
 
-function madeira_run_dev {
+  echo "xfce4-terminal not found"
+  return
+fi
 
-    madeira_init "${@}" || return
+for container in "${api_image_name}" "${ui_image_name}"; do
+  container_is_running=$(docker ps -q -f name="${container}")
+  if [ "${container_is_running}" ]; then
+    docker stop "${container}"
+  fi
+done
 
-    if ! which xfce4-terminal >/dev/null; then
-
-      echo "xfce4-terminal not found"
-      return
-    fi
-
-    api_container="${app}_api"
-    ui_container="${app}_ui"
-
-    for container in "${api_container}" "${ui_container}"; do
-      container_is_running=$(docker ps -q -f name="${container}")
-      if [ "${container_is_running}" ]; then
-        docker stop "${container}"
-      fi
-    done
-
-    xfce4-terminal \
-          --title strava_ui  --working-directory "${app_dir}" --command ./run_ui.sh \
-    --tab --title strava_api --working-directory "${app_dir}" --command ./run_api.sh
-}
+echo "Starting terminal for ${app} dev"
+xfce4-terminal \
+      --title strava_ui  --working-directory "${docker_dir}" --command ./run_ui.sh \
+--tab --title strava_api --working-directory "${docker_dir}" --command ./run_api.sh
